name: pykt_pt_emb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.17.2
  - pandas>=1.1.5 
  - scikit-learn 
  - pip
  - pip:
    - torch>=1.7.0 
    - wandb>=0.12.9 
    - entmax
    - tqdm
    - einops
